### ISSUE TITLE
Current status & Windows support - possible Unicode issue?

### ISSUE THREAD

**Issue by ideasean** [pmem/pynvm#21]
Just checking if this is the latest version of pynvm? It may not be working against the latest version of pmdk (built via vcpkg on Windows 10 & VS2017)

During pip install, I need to manually rename the pmdk obj files to remove the "lib" part of the name.

Running the account demo, the created file is jumbled unicode - 祭捡潣湵獴瀮敭潭橢漀獲  whereas it should be myaccounts.pmemobj. Running a second time fails.

It may be related to the following warning during compile time...

build\temp.win-amd64-3.6\Release\_pmem.c(933): warning C4133: 'return': incompatible types - from 'const wchar_t *' to 'const char *'
(there are approx 36 similar issues relating to wchar_t)

I recall getting this working on Windows a few months ago, but since then my build environment was wiped :-)

**Comment by pbalcer** [comment]
This project currently has no maintainer, and unfortunately there are no plans in the near future to resume development.
The current release is 0.3, and should be stable enough to experiment with, but performance might be lacking.

As for your problem: as part of our effort to port PMDK to Windows, we created entry points with `wchar_t *`. This change wasn't made in the FFI definitions in this project. I think solving this problem would be as simple as adding Windows specific entry points to `libex.py`, but it might require some python-equivalent of `#ifdef WIN32` so that linux isn't broken.

**Comment by ideasean** [comment]
I managed to get the Linux versions working using the latest pmdk on Ubuntu 18 and RHEL 7.5 (Python 3.6) however on running the pminvaders example it crashes after a few seconds with out of memory (zalloc). I increased the pool size and that let it run for a while, however on quit and resume it soon also crashes with a keyerror.

With the account demo code from the documentation I could also only make < 100 deposits before it also stopped with out of memory.

With Intel's Optane DIMMs coming to market soon I am hoping this project will get more attention :-)

**Comment by pbalcer** [comment]
I managed to successfully run pminvaders for some time after I increased the pool size to 80 megabytes. pynvm currently suffers from an efficiency problem where, due to many very small allocations, the internal fragmentation is quite large.

**Comment by ideasean** [comment]
@pbalcer I am wondering if this is just an implementation issue with this particular library (pynvm), or if there is a more fundamental issue that means simply replacing native python objects (like lists, dicts, etc) with pynvm-enabled objects is not really feasible. Ie for real-world applications, developers will need to take more hands on control of memory pre-allocation, assignment and de-allocation to reduce fragmentation. 

For example, I have an application that creates 5000+ objects, each with a dict of 0-500 deques with up to 50 tuple elements which are created at runtime based on various inbound datastreams running at up to 1000 updates per second on a single thread. Python native containers handle this quite easily. I suspect conversion to use persistent memory may be more challenging than drop-in library replacement?

**Comment by pbalcer** [comment]
The biggest problem with the pool size is that there is no such limit with DRAM allocations. Your pool is the entire DRAM heap, with swap file if configured. Add to that the virtual page mappings, lazy page allocations, and all the other tricks that the OS pulls under the covers, and you effectively never run out of memory, and if you do - the process gets killed before it can actually get `NULL` from `malloc()`. This is in contract with libpmemobj, which puts a hard limit and actually enforces it. The overheads are actually quite similar, you just don't see them in with volatile memory allocation.

With Python, the other problem is that it performs many very small allocations, which is inefficient and carries a large overhead in most types of allocators. From what I've heard, in CPython, and I'm guessing other implementations, there's a special bitmap-based allocation mechanism to workaround this. In order to eliminate this overhead also in pynvm, in libpmemobj we developed a slab-like custom allocation mechanism, which can be used to allocate arbitrarily small objects (even 1 byte ones) in a space- and time- efficient way. The intention is to use this mechanism in pynvm, if and when we get back to this topic.

I think most fragmentation-related issues can be solved at the container level, transparently to the user. But I also think that an explicit memory management could be useful.

But, I'm no Python expert, and there might be some trickery involved in python memory management that I'm not aware of. If you feel like we need to fundamentally shift our approach, please let us know.

**Comment by ideasean** [comment]
Understood, and thanks. When we are looking at Optane DC modules with 512GB per DIMM slot multiplied by a few slots, the future persistent pool is potentially larger than most current DRAM+swap configurations. The issue then becomes more a performance issue + ensuring de-allocated resources can be reclaimed efficiently while managing fragmentation issues. 

Hoping the Python support gets more attention in the near future. It might be worth putting something in the readme re current support status?
